import mongoose from "mongoose";
const Schema = mongoose.Schema;

if (process.env.DB_STRING) {
	mongoose.connect(process.env.DB_STRING);
} else {
	console.log("DB STRING NOT DEFINED");
}

const ArmorSchema = new Schema({
	index: { type: String, required: true }, //TODO: make this automatically created from name on new monster creation (assuming no duplicates?) Maybe also consider changing schema to have an id string instead
	name: { type: String, required: true },
	url: { type: String },
});

const ArmorClassSchema = new Schema({
	type: { type: String, required: true },
	value: { type: Number, required: true },
	armor: ArmorSchema,
	spell: ArmorSchema,
	condition: ArmorSchema,
});

/* const ProficiencySchema = new Schema({
	value: { type: Number, required: true },
	nested: {
	
	}
}); */

const MonsterSchema = new Schema({
	index: { type: String, required: true },
	name: { type: String, required: true },
	size: { type: String, required: true },
	type: { type: String, required: true },
	alignment: { type: String, required: true },
	armor_class: { type: [ArmorClassSchema], required: true },
	hit_points: { type: Number, required: true },
	hit_dice: { type: String, required: true },
	hit_points_roll: { type: String },
	strength: { type: Number, required: true },
	dexterity: { type: Number, required: true },
	constitution: { type: Number, required: true },
	intelligence: { type: Number, required: true },
	wisdom: { type: Number, required: true },
	charisma: { type: Number, required: true },
	//proficiences: {type: }
	damage_vulnerabilities: { type: [String] },
	damage_resistances: { type: [String] },
	damage_immunities: { type: [String] },
	condition_immunities: { type: [String] },
	//senses: {type: }
	languages: { type: String },
	challenge_rating: { type: Number, required: true },
	proficiency_bonus: { type: Number },
	xp: { type: Number, required: true },
	//special_abilities: {type: }
	//actions: {type: }
	//legendary_actions: {type: }
	url: { type: String }, // Same with definitions, do we need this?
}); //TODO: update schema with all required and optional params
//Note: Would be nice if this was or could be autogenerated eh?

export default mongoose.models.Monster ||
	mongoose.model("Monster", MonsterSchema);
