import mongoose from "mongoose";
const Schema = mongoose.Schema;

if (process.env.DB_STRING) {
	mongoose.connect(process.env.DB_STRING);
} else {
	console.log("DB STRING NOT DEFINED");
}

const MonsterSchema = new Schema({
	index: { type: String, required: true },
	name: { type: String, required: true },
}); //TODO: update schema with all required and optional params
//Note: Would be nice if this was or could be autogenerated eh?

export default mongoose.models.Monster ||
	mongoose.model("Monster", MonsterSchema);
